python_library(
  name = 'plugin',
  sources = rglobs('trueaccord/pants/*.py'),
  dependencies = [
  ],
  provides = setup_py(
    name = 'scalapb.pants',
    version = '0.1.5',
    description = 'ScalaPB plugin for Pants',
    url = 'https://github.com/zenreach/scalapb-pants',
    author = 'Nikhil Murthy',
    author_email = 'nikhil@zenreach.com',
    license = 'Apache License, Version 2.0',
    zip_safe = True,
    classifiers = [
      'Intended Audience :: Developers',
      'License :: OSI Approved :: Apache Software License',
      'Operating System :: OS Independent',
      'Programming Language :: Python',
    ]
  )
)
